export const STRUCTURE_FORMS = ['LATTICE', 'MONOPOLE', 'GUYED', 'CONCRETE_POLE', 'WOOD_POLE'];
export const TOWER_FUNCTIONS = ['SUSPENSION', 'TENSION', 'TERMINAL', 'TRANSPOSITION', 'CROSSING'];

export const PURPOSES = ['STEP_UP', 'STEP_DOWN', 'SWITCHING', 'DISTRIBUTION'];
export const TECHNOLOGIES = ['AIS', 'GIS', 'HYBRID', 'RMU', 'PAD', 'MOBILE'];
export const BUSBAR_SCHEMES = ['SINGLE', 'DOUBLE', 'RING', 'BREAKER_AND_A_HALF', 'MESH'];

export const SKU_CATEGORIES = ['HARDWARE','INSULATOR','BREAKER','CT','PT','TRANSFORMER','RELAY','STEEL_MEMBER','BOLT','CABLE'];
export const COMPAT_ASSET_TYPES = ['TOWER', 'SUBSTATION'];

export const ASSET_TYPES = ['TOWER', 'SUBSTATION', 'TRANSFORMER', 'LINE_BAY'];
export const ASSET_STATUS = ['IN_SERVICE', 'SPARE', 'RETIRED'];